/* AUTO-GENERATED — DO NOT EDIT.
 * Source of truth: shared/contract/. Run `npm run sync:shared` after editing it.
 */
/**
 * Shared data-contract constants for the VisionKart apps.
 *
 * These are the field VALUES that both the storefront (`visionkart-web`) and the
 * admin portal (`admin-portal`) must agree on. Historically these lived as magic
 * strings duplicated across both apps and drifted (e.g. discountType 'fixed' vs
 * 'flat', order status 'Shipping' vs 'Shipped'), causing customer-facing bugs.
 * Keep the vocabulary here and import it in both apps.
 *
 * Canonical source: shared/contract/ — do not edit the per-app copies under
 * src/shared/ (they are generated by `npm run sync:shared`).
 */

/** Order lifecycle status values written to `orders.status`. */
export const ORDER_STATUS = Object.freeze({
  // Storefront-created
  ORDERED: 'Ordered',
  AWAITING_PAYMENT: 'Awaiting Payment',
  AWAITING_VERIFICATION: 'Awaiting Verification',
  // Backend-created (CCAvenue payment-response callback on a failed charge).
  // Not in ORDER_STATUS_OPTIONS: it is payment-flow-managed, not something an
  // admin should set by hand.
  PAYMENT_FAILED: 'Payment Failed',
  // Admin-managed
  PENDING: 'Pending',
  PROCESSING: 'Processing',
  SHIPPING: 'Shipping',
  SHIPPED: 'Shipped',
  DELIVERED: 'Delivered',
  CANCELLED: 'Cancelled',
  RETURNED: 'Returned',
});

/** Admin-selectable status values (order shown in the admin dropdown). */
export const ORDER_STATUS_OPTIONS = Object.freeze([
  ORDER_STATUS.PENDING,
  ORDER_STATUS.ORDERED,
  ORDER_STATUS.PROCESSING,
  ORDER_STATUS.SHIPPING,
  ORDER_STATUS.SHIPPED,
  ORDER_STATUS.DELIVERED,
  ORDER_STATUS.CANCELLED,
  ORDER_STATUS.RETURNED,
]);

/** Product availability labels stored on `products.status`. */
export const PRODUCT_STATUS = Object.freeze({
  IN_STOCK: 'In Stock',
  OUT_OF_STOCK: 'Out of Stock',
  DISCONTINUED: 'Discontinued',
});

/** Coupon `discountType` values. */
export const DISCOUNT_TYPE = Object.freeze({
  PERCENTAGE: 'percentage',
  FIXED: 'fixed',
});

/**
 * GST rate by product category. Sunglasses are taxed at 18%, everything else at
 * 12%. Both the cart and checkout must use the same rule.
 */
export function getGstRate(category) {
  return category === 'Sunglasses' ? 0.18 : 0.12;
}
